import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "../../components/Navbar/Navigation";
import Providers from "./lib/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pure Ledger",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navigation />
          {children}
        </Providers>
      </body>
    </html>
  );
}
